sudo: required
services:
  - docker
before_install:
  - sudo apt-get install jq
env:
  - ADDON="nextcloud" ARCHS="--armhf"
  - ADDON="python_exec"
script:
  - docker login -u $DOCKER_USER -p $DOCKER_PASS
  - ./build.sh $ADDON 
